(function(){function i(a,b,d){try{if(M&&a.forEach===M)a.forEach(b,d);else if(E(a.length))for(var e=0,f=a.length;e<f;e++)b.call(d,a[e],e,a);else for(e in a)F.call(a,e)&&b.call(d,a[e],e,a)}catch(g){if(g!=N)throw g;}return a}function q(a,b,d){if(O&&a.map===O)return a.map(b,d);var e=[];i(a,function(f,g,h){e[e.length]=b.call(d,f,g,h)});return e}function n(a,b,d,e){if(P&&a.reduce===P){if(e)b=v(b,e);return a.reduce(b,d)}i(a,function(f,g,h){d=b.call(e,d,f,g,h)});return d}function Q(a,b,d,e){if(R&&a.reduceRight===
R){if(e)b=v(b,e);return a.reduceRight(b,d)}a=S(k(a)).reverse();return n(a,b,d,e)}function o(a,b,d){if(T&&a.filter===T)return a.filter(b,d);var e=[];i(a,function(f,g,h){if(b.call(d,f,g,h))e[e.length]=f});return e}function G(a,b,d){b=b||p;if(U&&a.every===U)return a.every(b,d);var e=true;i(a,function(f,g,h){(e=e&&b.call(d,f,g,h))||r()});return e}function V(a,b,d){b=b||p;if(W&&a.some===W)return a.some(b,d);var e=false;i(a,function(f,g,h){if(e=b.call(d,f,g,h))r()});return e}function w(a,b){if(x&&a.indexOf===
x)return a.indexOf(b)!=-1;var d=false;i(a,function(e){if(d=e===b)r()});return d}function y(a,b){return q(a,function(d){return d[b]})}function X(a,b,d){if(!b&&l(a))return Math.max.apply(Math,a);var e={computed:-Infinity};i(a,function(f,g,h){g=b?b.call(d,f,g,h):f;g>=e.computed&&(e={value:f,computed:g})});return e.value}function k(a){if(!a)return[];if(a.toArray)return a.toArray();if(l(a))return a;if(Y(a))return H.call(a);return Z(a)}function $(a,b,d){return b&&!d?H.call(a,0,b):a[0]}function m(a,b,d){return H.call(a,
aa(b)||d?1:b)}function ba(a){return a[a.length-1]}function ca(a){return n(a,function(b,d){if(l(d))return b.concat(ca(d));b[b.length]=d;return b},[])}function da(a,b){return n(a,function(d,e,f){if(0==f||(b===true?ba(d)!=e:!w(d,e)))d[d.length]=e;return d},[])}function ea(a,b){if(x&&a.indexOf===x)return a.indexOf(b);for(var d=0,e=a.length;d<e;d++)if(a[d]===b)return d;return-1}function fa(a,b,d){var e=k(arguments),f=e.length<=1;a=f?0:e[0];b=f?e[0]:e[1];d=e[2]||1;e=Math.ceil((b-a)/d);if(e<=0)return[];
e=new z(e);f=a;for(var g=0;;f+=d){if((d>0?f-b:b-f)>=0)return e;e[g++]=f}}function v(a,b){var d=m(arguments,2);return function(){return a.apply(b||{},d.concat(k(arguments)))}}function ga(a,b){var d=m(arguments,2);return setTimeout(function(){return a.apply(a,d)},b)}function oa(a){if(l(a))return fa(0,a.length);var b=[];for(var d in a)if(F.call(a,d))b[b.length]=d;return b}function Z(a){return q(a,p)}function A(a){return o(B(a),function(b){return ha(a[b])}).sort()}function ia(a){i(m(arguments),function(b){for(var d in b)a[d]=
b[d]});return a}function S(a){if(l(a))return a.slice(0);return ia({},a)}function ja(a,b){if(a===b)return true;var d=typeof a;if(d!=typeof b)return false;if(a==b)return true;if(!a&&b||a&&!b)return false;if(a.isEqual)return a.isEqual(b);if(I(a)&&I(b))return a.getTime()===b.getTime();if(J(a)&&J(b))return false;if(K(a)&&K(b))return a.source===b.source&&a.global===b.global&&a.ignoreCase===b.ignoreCase&&a.multiline===b.multiline;if(d!=="object")return false;if(a.length&&a.length!==b.length)return false;
d=B(a);var e=B(b);if(d.length!=e.length)return false;for(var f in a)if(!(f in b)||!ja(a[f],b[f]))return false;return true}function l(a){return!!(a&&a.concat&&a.unshift&&!a.callee)}function Y(a){return!!(a&&a.callee)}function ha(a){return!!(a&&a.constructor&&a.call&&a.apply)}function ka(a){return!!(a===""||a&&a.charCodeAt&&a.substr)}function E(a){return a===+a||pa.call(a)==="[object Number]"}function I(a){return!!(a&&a.getTimezoneOffset&&a.setUTCFullYear)}function K(a){return!!(a&&a.test&&a.exec&&
(a.ignoreCase||a.ignoreCase===false))}function J(a){return E(a)&&isNaN(a)}function aa(a){return typeof a=="undefined"}function p(a){return a}function r(){throw N;}function la(a){i(A(a),function(b){var d=s[b]=a[b];t[b]=function(){var e=k(arguments);qa.call(e,this.w);return L(d.apply(s,e),this.c)}})}function L(a,b){return b?new C(a,1):a}var D=this,ra=D._,N=typeof StopIteration!=="undefined"?StopIteration:"__break__",sa=0,z=Array,u=Object,j=z.prototype,ma=u.prototype,H=j.slice,qa=j.unshift,pa=ma.toString,
F=ma.hasOwnProperty,M=j.forEach,O=j.map,P=j.reduce,R=j.reduceRight,T=j.filter,U=j.every,W=j.some,x=j.indexOf,na=j.lastIndexOf;l=z.isArray||_isArray;var B=u.keys||oa,C=function(a,b){this.w=a;this.c=!!b},t=C.prototype,s=function(a){return new C(a)};u=function(a){return new C(a,1)};if(typeof exports!=="undefined"){exports._=s;exports.__=u}D._=s;D.__=u;la({each:i,forEach:i,map:q,reduce:n,inject:n,foldl:n,reduceRight:Q,foldr:Q,detect:function(a,b,d){var e;i(a,function(f,g,h){if(b.call(d,f,g,h)){e=f;r()}});
return e},filter:o,select:o,reject:function(a,b,d){var e=[];i(a,function(f,g,h){b.call(d,f,g,h)||(e[e.length]=f)});return e},every:G,all:G,some:V,any:V,include:w,contains:w,invoke:function(a,b){var d=m(arguments,2);return q(a,function(e){return(b?e[b]:e).apply(e,d)})},pluck:y,max:X,min:function(a,b,d){if(!b&&l(a))return Math.min.apply(Math,a);var e={computed:Infinity};i(a,function(f,g,h){g=b?b.call(d,f,g,h):f;g<e.computed&&(e={value:f,computed:g})});return e.value},sortBy:function(a,b,d){return y(q(a,
function(e,f,g){return{value:e,criteria:b.call(d,e,f,g)}}).sort(function(e,f){var g=e.criteria,h=f.criteria;return g<h?-1:g>h?1:0}),"value")},sortedIndex:function(a,b,d){d=d||p;for(var e=0,f=a.length;e<f;){var g=e+f>>1;d(a[g])<d(b)?(e=g+1):(f=g)}return e},toArray:k,size:function(a){return k(a).length},first:$,head:$,rest:m,tail:m,last:ba,compact:function(a){return o(a,function(b){return!!b})},flatten:ca,without:function(a){var b=m(arguments);return o(a,function(d){return!w(b,d)})},uniq:da,intersect:function(a){var b=
b(arguments);return o(da(a),function(d){return G(b,function(e){return ea(e,d)>=0})})},zip:function(){for(var a=k(arguments),b=X(y(a,"length")),d=new z(b),e=0;e<b;e++)d[e]=y(a,""+e);return d},indexOf:ea,lastIndexOf:function(a,b){if(na&&a.lastIndexOf===na)return a.lastIndexOf(b);for(var d=a.length;d--;)if(a[d]===b)return d;return-1},range:fa,bind:v,bindAll:function(a){var b=m(arguments);if(b.length==0)b=A(a);i(b,function(d){a[d]=v(a[d],a)});return a},memoize:function(a,b){var d={};b=b||p;return function(){var e=
b.apply(this,arguments);return e in d?d[e]:(d[e]=a.apply(this,arguments))}},delay:ga,defer:function(a){return ga.apply(s,[a,1].concat(m(arguments)))},wrap:function(a,b){return function(){var d=[a].concat(k(arguments));return b.apply(b,d)}},compose:function(){var a=k(arguments);return function(){for(var b=k(arguments),d=a.length;--d;)b=[a[d].apply(this,b)];return b[0]}},keys:B,values:Z,functions:A,methods:A,extend:ia,clone:S,tap:function(a,b){b(a);return a},isEqual:ja,isEmpty:function(a){if(l(a)||
ka(a))return a.length===0;for(var b in a)if(F.call(a,b))return false;return true},isElement:function(a){return!!(a&&a.nodeType==1)},isArray:l,isArguments:Y,isFunction:ha,isString:ka,isNumber:E,isBoolean:function(a){return a===true||a===false},isDate:I,isRegExp:K,isNaN:J,isNull:function(a){return a===null},isUndefined:aa,noConflict:function(){D._=ra;return this},identity:p,times:function(a,b,d){for(var e=0;e<a;e++)b.call(d,e)},breakLoop:r,mixin:la,uniqueId:function(a){var b=sa++;return a?a+b:b},template:function(a,
b){var d=new RegExp("'(?=[^"+c.end.substr(0,1)+"]*"+c.end.replace(/([.*+?^${}()|[\]\/\\])/g,"\\$1")+")","g");d=new Function("obj","var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(d,"\u2704").split("'").join("\\'").split("\u2704").join("'").replace(c.interpolate,"',$1,'").split(c.start).join("');").split(c.end).join("__p.push('")+"');}return __p.join('');");return b?d(b):d},VERSION:"1.1.0",
templateSettings:{start:"<%",end:"%>",interpolate:/<%=(.+?)%>/g}});i(["pop","push","reverse","shift","sort","splice","unshift"],function(a){var b=j[a];t[a]=function(){b.apply(this.w,arguments);return L(this.w,this.c)}});i(["concat","join","slice"],function(a){var b=j[a];t[a]=function(){return L(b.apply(this.w,arguments),this.c)}});t.chain=function(){this.c=true;return this};t.value=function(){return this.w}})();
